# Testing `EntityFusionPolars` on the PPP dataset

Exercises `Entity_Fusion_Polars.py` against `test_data/100k.csv` (a PPP loan extract — despite the filename it's actually ~968k rows, so this doubles as a scale check against the ~1M-row target).

We treat `BorrowerName` + `BorrowerAddress` + `BorrowerZip` as exact-match identifiers with `k_required=2` (a pair must agree on at least 2 of the 3 columns to link) and walk through: the pre-clustering block-size check, timing the full run, and inspecting `cluster_stats` for merges worth reviewing.

In [1]:
import time
import polars as pl

from Entity_Fusion_Polars import EntityFusionPolars

pl.Config.set_tbl_rows(20)

polars.config.Config

## Load & normalize

Exact matching has no tolerance for casing/whitespace drift the way cosine matching does, so the identifier columns need normalizing before they're usable as exact-match keys.

In [2]:
df = pl.read_csv("test_data/100k.csv", infer_schema_length=5000)
df = df.with_row_index("record_id").with_columns(pl.col("record_id").cast(pl.Utf8))
df = df.with_columns(
    [
        pl.col("BorrowerName").str.strip_chars().str.to_uppercase(),
        pl.col("BorrowerAddress").str.strip_chars().str.to_uppercase(),
        pl.col("BorrowerZip").cast(pl.Utf8).str.strip_chars(),
    ]
)

print(f"{df.height:,} rows")
df.select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "BorrowerCity").head()

968,525 rows

shape: (5, 5)
┌───────────┬──────────────────────────┬───────────────────────┬─────────────┬──────────────────┐
│ record_id ┆ BorrowerName             ┆ BorrowerAddress       ┆ BorrowerZip ┆ BorrowerCity     │
│ ---       ┆ ---                      ┆ ---                   ┆ ---         ┆ ---              │
│ str       ┆ str                      ┆ str                   ┆ str         ┆ str              │
╞═══════════╪══════════════════════════╪═══════════════════════╪═════════════╪══════════════════╡
│ 0         ┆ SUMTER COATINGS, INC.    ┆ 2410 HIGHWAY 15 SOUTH ┆ 29150-9662  ┆ Sumter           │
│ 1         ┆ PLEASANT PLACES, INC.    ┆ 7684 SOUTHRAIL ROAD   ┆ 29420-9000  ┆ North Charleston │
│ 2         ┆ BOYER CHILDREN'S CLINIC  ┆ 1850 BOYER AVE E      ┆ 98112-2922  ┆ SEATTLE          │
│ 3         ┆ KIRTLEY CONSTRUCTION INC ┆ 1661 MARTIN RANCH RD  ┆ 92407-1740  ┆ SAN BERNARDINO   │
│ 4         ┆ AERO BOX LLC             ┆ null                  ┆ null        ┆ null             │
└───────────┴──────────────────────────┴───────────────────────┴─────────────┴──────────────────┘

## Pre-clustering block-size check

Run this before the expensive part: for each match column, how many distinct rows share the same value? A runaway value (a placeholder address, a common name) would blow up the pairwise self-join downstream — better to see it here first.

In [21]:
linker = EntityFusionPolars(
    record_id_col="record_id",
    match_columns=[
        "BorrowerAddress",
        # "BorrowerZip",
        {"column": "BorrowerName", "block_on": ["BorrowerState"]},
    ],
    k_required=2,
    block_cap=2000,
)

t0 = time.time()
blocks = linker.preview_blocks(df)
print(f"preview_blocks: {time.time() - t0:.2f}s")
print(f"largest block: {blocks['n_hash_ids'].max()} (block_cap={linker.block_cap})")
blocks.head(10)

preview_blocks: 0.71s
largest block: 92 (block_cap=2000)

shape: (10, 4)
┌─────────────────┬───────┬────────────────────────────────┬────────────┐
│ match_column    ┆ block ┆ value                          ┆ n_hash_ids │
│ ---             ┆ ---   ┆ ---                            ┆ ---        │
│ str             ┆ str   ┆ str                            ┆ u32        │
╞═════════════════╪═══════╪════════════════════════════════╪════════════╡
│ BorrowerAddress ┆       ┆ PO BOX                         ┆ 92         │
│ BorrowerAddress ┆       ┆ 1140 RESERVOIR AVE             ┆ 48         │
│ BorrowerAddress ┆       ┆ 2390 TOWER DR                  ┆ 48         │
│ BorrowerAddress ┆       ┆ 11410 COMMON OAKS DR           ┆ 43         │
│ BorrowerAddress ┆       ┆ TBD                            ┆ 42         │
│ BorrowerAddress ┆       ┆ 830 W TRAILCREEK DR            ┆ 41         │
│ BorrowerAddress ┆       ┆ 7 PEARL CT                     ┆ 41         │
│ BorrowerAddress ┆       ┆ 14504 HERTZ QUAIL SPRINGS PKWY ┆ 37         │
│ BorrowerAddress ┆       ┆ 807 DORSEY STREET              ┆ 36         │
│ BorrowerAddress ┆       ┆ 1445 5TH ST                    ┆ 35         │
└─────────────────┴───────┴────────────────────────────────┴────────────┘

The largest block is well under `block_cap`, so nothing gets excluded here — safe to run the full pipeline.

## Run clustering

In [4]:
manual_address_clusters = pl.DataFrame({
    "manual_cluster_id": ["ADDR_ALIAS_001", "ADDR_ALIAS_001"],
    "field": ["BorrowerAddress", "BorrowerAddress"],
    "value": ["7 PEARL CT", "11410 COMMON OAKS DR"],
    "active": [True, True],
})

out = linker.cluster(
    df,
    manual_identifier_clusters=manual_address_clusters,
)

In [5]:
t0 = time.time()
out = linker.cluster(df)
elapsed = time.time() - t0
print(f"cluster(): {elapsed:.2f}s for {df.height:,} rows")

records, stats = out["records"], out["cluster_stats"]
print(f"{stats.height:,} clusters total")

cluster(): 9.06s for 968,525 rows
819,527 clusters total

## Manual decision smoke test

Create a tiny persistent review table and force records `396923` and `538365` into the same component with a `must_link` decision. The baseline `records`/`stats` outputs above stay unchanged; `manual_out` shows the override behavior separately.

In [6]:
manual_decision_records = ["396923", "538365"]

manual_decisions = pl.DataFrame({
    "record_id_a": [manual_decision_records[0]],
    "record_id_b": [manual_decision_records[1]],
    "decision": ["must_link"],
    "reviewer": ["notebook_test"],
    "reason": ["manual source-of-truth smoke test"],
    "active": [True],
})

baseline_pair = (
    records
    .filter(pl.col("record_id").is_in(manual_decision_records))
    .select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id", "cluster_id", "stable_cluster_id")
    .sort("record_id")
)

t0 = time.time()
manual_out = linker.cluster(df, manual_decisions=manual_decisions)
manual_elapsed = time.time() - t0

manual_records = manual_out["records"]
manual_pair = (
    manual_records
    .filter(pl.col("record_id").is_in(manual_decision_records))
    .select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id", "cluster_id", "stable_cluster_id")
    .sort("record_id")
)

print(f"manual cluster(): {manual_elapsed:.2f}s")
print("baseline cluster ids:")
print(baseline_pair)
print("manual-decision cluster ids:")
print(manual_pair)
print("manual_edges:")
print(manual_out["manual_edges"])
print("manual_conflicts:")
print(manual_out["manual_conflicts"])

assert manual_pair["cluster_id"].n_unique() == 1

manual cluster(): 9.23s
baseline cluster ids:
shape: (2, 7)
┌───────────┬──────────────┬──────────────┬─────────────┬──────────────┬────────────┬──────────────┐
│ record_id ┆ BorrowerName ┆ BorrowerAddr ┆ BorrowerZip ┆ hash_id      ┆ cluster_id ┆ stable_clust │
│ ---       ┆ ---          ┆ ess          ┆ ---         ┆ ---          ┆ ---        ┆ er_id        │
│ str       ┆ str          ┆ ---          ┆ str         ┆ u64          ┆ str        ┆ ---          │
│           ┆              ┆ str          ┆             ┆              ┆            ┆ str          │
╞═══════════╪══════════════╪══════════════╪═════════════╪══════════════╪════════════╪══════════════╡
│ 396923    ┆ ALBUQUERQUE  ┆ 2390 TOWER   ┆ 71201-5760  ┆ 168105983596 ┆ 1167       ┆ AUTO_1046458 │
│           ┆ HOSPITALITY  ┆ DR           ┆             ┆ 10691656     ┆            ┆ 05202085965  │
│           ┆ LLC          ┆              ┆             ┆              ┆            ┆              │
│ 538365    ┆ APPLE HOTEL  ┆ 11410 COMMON ┆ 27614-7002  ┆ 584407348024 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ HOLDINGS LLC ┆ OAKS DR      ┆             ┆ 3185136      ┆            ┆ 95102524726  │
└───────────┴──────────────┴──────────────┴─────────────┴──────────────┴────────────┴──────────────┘
manual-decision cluster ids:
shape: (2, 7)
┌───────────┬──────────────┬──────────────┬─────────────┬──────────────┬────────────┬──────────────┐
│ record_id ┆ BorrowerName ┆ BorrowerAddr ┆ BorrowerZip ┆ hash_id      ┆ cluster_id ┆ stable_clust │
│ ---       ┆ ---          ┆ ess          ┆ ---         ┆ ---          ┆ ---        ┆ er_id        │
│ str       ┆ str          ┆ ---          ┆ str         ┆ u64          ┆ str        ┆ ---          │
│           ┆              ┆ str          ┆             ┆              ┆            ┆ str          │
╞═══════════╪══════════════╪══════════════╪═════════════╪══════════════╪════════════╪══════════════╡
│ 396923    ┆ ALBUQUERQUE  ┆ 2390 TOWER   ┆ 71201-5760  ┆ 168105983596 ┆ 1167       ┆ AUTO_1046458 │
│           ┆ HOSPITALITY  ┆ DR           ┆             ┆ 10691656     ┆            ┆ 05202085965  │
│           ┆ LLC          ┆              ┆             ┆              ┆            ┆              │
│ 538365    ┆ APPLE HOTEL  ┆ 11410 COMMON ┆ 27614-7002  ┆ 584407348024 ┆ 1167       ┆ AUTO_1046458 │
│           ┆ HOLDINGS LLC ┆ OAKS DR      ┆             ┆ 3185136      ┆            ┆ 05202085965  │
└───────────┴──────────────┴──────────────┴─────────────┴──────────────┴────────────┴──────────────┘
manual_edges:
shape: (1, 2)
┌─────────────────────┬──────────────────────┐
│ a                   ┆ b                    │
│ ---                 ┆ ---                  │
│ u64                 ┆ u64                  │
╞═════════════════════╪══════════════════════╡
│ 5844073480243185136 ┆ 16810598359610691656 │
└─────────────────────┴──────────────────────┘
manual_conflicts:
shape: (0, 9)
┌─────────────┬─────────────┬──────────┬───────────┬───┬─────┬─────┬────────────┬───────────────┐
│ record_id_a ┆ record_id_b ┆ decision ┆ hash_id_a ┆ … ┆ a   ┆ b   ┆ cluster_id ┆ conflict_type │
│ ---         ┆ ---         ┆ ---      ┆ ---       ┆   ┆ --- ┆ --- ┆ ---        ┆ ---           │
│ str         ┆ str         ┆ str      ┆ u64       ┆   ┆ u64 ┆ u64 ┆ str        ┆ str           │
╞═════════════╪═════════════╪══════════╪═══════════╪═══╪═════╪═════╪════════════╪═══════════════╡
└─────────────┴─────────────┴──────────┴───────────┴───┴─────┴─────┴────────────┴───────────────┘

## Manual identifier-cluster smoke test

This uses `BorrowerName` as the identifier field because this PPP notebook does not include EIN. The pattern is the same for EIN: put the identifier values in the same `manual_cluster_id`, and every current row carrying either value joins the same component.

### EIN-shaped toy example

This is the intended source-of-truth shape for identifier aliases: two EIN values share one `manual_cluster_id`, so all records carrying either EIN join the same component.

In [7]:
ein_demo = pl.DataFrame([
    {"record_id": "E1A", "ein": "12-3456789", "phone": "P1"},
    {"record_id": "E1B", "ein": "12-3456789", "phone": "P2"},
    {"record_id": "E2A", "ein": "98-7654321", "phone": "P3"},
    {"record_id": "E2B", "ein": "98-7654321", "phone": "P4"},
    {"record_id": "E3A", "ein": "11-1111111", "phone": "P5"},
])

ein_linker = EntityFusionPolars(
    record_id_col="record_id",
    match_columns=["ein", "phone"],
    k_required=1,
)

ein_baseline = ein_linker.cluster(ein_demo)

manual_ein_identifier_clusters = pl.DataFrame({
    "manual_cluster_id": ["EIN_ALIAS_001", "EIN_ALIAS_001"],
    "field": ["ein", "ein"],
    "value": ["12-3456789", "98-7654321"],
    "active": [True, True],
})

ein_manual = ein_linker.cluster(
    ein_demo,
    manual_identifier_clusters=manual_ein_identifier_clusters,
)

print("manual_ein_identifier_clusters:")
print(manual_ein_identifier_clusters)
print("baseline EIN clusters:")
print(ein_baseline["records"].select("record_id", "ein", "cluster_id", "stable_cluster_id").sort("record_id"))
print("manual EIN alias clusters:")
print(ein_manual["records"].select("record_id", "ein", "cluster_id", "stable_cluster_id").sort("record_id"))
print("manual_identifier_edges:")
print(ein_manual["manual_identifier_edges"])

assert (
    ein_manual["records"]
    .filter(pl.col("ein").is_in(["12-3456789", "98-7654321"]))["cluster_id"]
    .n_unique()
    == 1
)

manual_ein_identifier_clusters:
shape: (2, 4)
┌───────────────────┬───────┬────────────┬────────┐
│ manual_cluster_id ┆ field ┆ value      ┆ active │
│ ---               ┆ ---   ┆ ---        ┆ ---    │
│ str               ┆ str   ┆ str        ┆ bool   │
╞═══════════════════╪═══════╪════════════╪════════╡
│ EIN_ALIAS_001     ┆ ein   ┆ 12-3456789 ┆ true   │
│ EIN_ALIAS_001     ┆ ein   ┆ 98-7654321 ┆ true   │
└───────────────────┴───────┴────────────┴────────┘
baseline EIN clusters:
shape: (5, 4)
┌───────────┬────────────┬────────────────────────┬───────────────────────────┐
│ record_id ┆ ein        ┆ cluster_id             ┆ stable_cluster_id         │
│ ---       ┆ ---        ┆ ---                    ┆ ---                       │
│ str       ┆ str        ┆ str                    ┆ str                       │
╞═══════════╪════════════╪════════════════════════╪═══════════════════════════╡
│ E1A       ┆ 12-3456789 ┆ 1                      ┆ AUTO_10409277717357437705 │
│ E1B       ┆ 12-3456789 ┆ 1                      ┆ AUTO_10409277717357437705 │
│ E2A       ┆ 98-7654321 ┆ 2                      ┆ AUTO_11907445488209632197 │
│ E2B       ┆ 98-7654321 ┆ 2                      ┆ AUTO_11907445488209632197 │
│ E3A       ┆ 11-1111111 ┆ UN_5956737580923855349 ┆ UN_5956737580923855349    │
└───────────┴────────────┴────────────────────────┴───────────────────────────┘
manual EIN alias clusters:
shape: (5, 4)
┌───────────┬────────────┬────────────────────────┬────────────────────────┐
│ record_id ┆ ein        ┆ cluster_id             ┆ stable_cluster_id      │
│ ---       ┆ ---        ┆ ---                    ┆ ---                    │
│ str       ┆ str        ┆ str                    ┆ str                    │
╞═══════════╪════════════╪════════════════════════╪════════════════════════╡
│ E1A       ┆ 12-3456789 ┆ 1                      ┆ EIN_ALIAS_001          │
│ E1B       ┆ 12-3456789 ┆ 1                      ┆ EIN_ALIAS_001          │
│ E2A       ┆ 98-7654321 ┆ 1                      ┆ EIN_ALIAS_001          │
│ E2B       ┆ 98-7654321 ┆ 1                      ┆ EIN_ALIAS_001          │
│ E3A       ┆ 11-1111111 ┆ UN_5956737580923855349 ┆ UN_5956737580923855349 │
└───────────┴────────────┴────────────────────────┴────────────────────────┘
manual_identifier_edges:
shape: (3, 2)
┌──────────────────────┬──────────────────────┐
│ a                    ┆ b                    │
│ ---                  ┆ ---                  │
│ u64                  ┆ u64                  │
╞══════════════════════╪══════════════════════╡
│ 10409277717357437705 ┆ 11863100295317015234 │
│ 10409277717357437705 ┆ 15582242622374500965 │
│ 10409277717357437705 ┆ 11907445488209632197 │
└──────────────────────┴──────────────────────┘

In [8]:
manual_address_clusters = pl.DataFrame({
    "manual_cluster_id": ["ADDR_ALIAS_001", "ADDR_ALIAS_001"],
    "field": ["BorrowerAddress", "BorrowerAddress"],
    "value": ["7 PEARL CT", "11410 COMMON OAKS DR"],
    "active": [True, True],
})

address_out = linker.cluster(
    df,
    manual_identifier_clusters=manual_address_clusters,
)

In [9]:
address_out['records'].head()

shape: (5, 57)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ record_id ┆ LoanNumbe ┆ DateAppro ┆ SBAOffice ┆ … ┆ Forgivene ┆ hash_id   ┆ cluster_i ┆ stable_c │
│ ---       ┆ r         ┆ ved       ┆ Code      ┆   ┆ ssDate    ┆ ---       ┆ d         ┆ luster_i │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ u64       ┆ ---       ┆ d        │
│           ┆ i64       ┆ str       ┆ i64       ┆   ┆ str       ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 954750770 ┆ 05/01/202 ┆ 464       ┆ … ┆ 11/20/202 ┆ 451537429 ┆ UN_451537 ┆ UN_45153 │
│           ┆ 4         ┆ 0         ┆           ┆   ┆ 0         ┆ 749584847 ┆ 429749584 ┆ 74297495 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 847       ┆ 84847    │
│ 1         ┆ 977767770 ┆ 05/01/202 ┆ 464       ┆ … ┆ 08/12/202 ┆ 786069201 ┆ UN_786069 ┆ UN_78606 │
│           ┆ 4         ┆ 0         ┆           ┆   ┆ 1         ┆ 034094123 ┆ 201034094 ┆ 92010340 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆ 1238      ┆ 941238   │
│ 2         ┆ 579140770 ┆ 05/01/202 ┆ 1013      ┆ … ┆ 02/10/202 ┆ 711299411 ┆ UN_711299 ┆ UN_71129 │
│           ┆ 2         ┆ 0         ┆           ┆   ┆ 1         ┆ 188208773 ┆ 411188208 ┆ 94111882 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆ 7739      ┆ 087739   │
│ 3         ┆ 622356770 ┆ 05/01/202 ┆ 920       ┆ … ┆ 09/10/202 ┆ 692930942 ┆ UN_692930 ┆ UN_69293 │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ 1         ┆ 281287501 ┆ 942281287 ┆ 09422812 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆ 5014      ┆ 875014   │
│ 4         ┆ 966243770 ┆ 05/01/202 ┆ 101       ┆ … ┆ 04/08/202 ┆ 163309279 ┆ UN_163309 ┆ UN_16330 │
│           ┆ 2         ┆ 0         ┆           ┆   ┆ 1         ┆ 704876476 ┆ 279704876 ┆ 92797048 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 39        ┆ 47639     ┆ 7647639  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
# identifier_alias_records = ["396923", "538365"]

# identifier_alias_values = (
#     records
#     .filter(pl.col("record_id").is_in(identifier_alias_records))
#     .select("record_id", "BorrowerName")
#     .sort("record_id")
# )

# manual_identifier_clusters = identifier_alias_values.select(
#     manual_cluster_id=pl.lit("BORROWER_NAME_ALIAS_001"),
#     field=pl.lit("BorrowerName"),
#     value=pl.col("BorrowerName"),
#     reviewer=pl.lit("notebook_test"),
#     reason=pl.lit("manual identifier-alias smoke test"),
#     active=pl.lit(True),
# )

# alias_values = manual_identifier_clusters["value"].to_list()
# baseline_identifier_alias_records = (
#     records
#     .filter(pl.col("BorrowerName").is_in(alias_values))
#     .select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id", "cluster_id", "stable_cluster_id")
#     .sort(["BorrowerName", "record_id"])
# )

# t0 = time.time()
# identifier_alias_out = linker.cluster(
#     df,
#     manual_identifier_clusters=manual_identifier_clusters,
# )
# identifier_alias_elapsed = time.time() - t0

# identifier_alias_records_out = (
#     identifier_alias_out["records"]
#     .filter(pl.col("BorrowerName").is_in(alias_values))
#     .select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id", "cluster_id", "stable_cluster_id")
#     .sort(["BorrowerName", "record_id"])
# )

# print(f"manual identifier cluster(): {identifier_alias_elapsed:.2f}s")
# print("manual_identifier_clusters source table:")
# print(manual_identifier_clusters)
# print("baseline affected records:")
# print(baseline_identifier_alias_records)
# print("manual-identifier affected records:")
# print(identifier_alias_records_out)
# print("manual_identifier_edges:")
# print(identifier_alias_out["manual_identifier_edges"])

# assert identifier_alias_records_out["cluster_id"].n_unique() == 1
# assert identifier_alias_out["manual_identifier_edges"].height >= 1

## Overall summary

Split clusters into real matches (`cluster_id` is a plain integer) vs untouched singletons (`UN_` prefix).

In [11]:
matched = stats.filter(~pl.col("cluster_id").str.starts_with("UN_"))
singletons = stats.filter(pl.col("cluster_id").str.starts_with("UN_"))

print(f"matched clusters (size >= 2): {matched.height:,}")
print(f"untouched singletons:         {singletons.height:,}")
print(f"rows in matched clusters:     {matched['n_primary_ids'].sum():,}")
print(f"rows untouched:               {singletons['n_primary_ids'].sum():,}")
print(f"overall dedup_ratio (matched only), mean: {matched['dedup_ratio'].mean():.2f}")

matched clusters (size >= 2): 97,513
untouched singletons:         722,014
rows in matched clusters:     220,471
rows untouched:               748,054
overall dedup_ratio (matched only), mean: 1.01

## Largest clusters

Sorted by row count. Worth eyeballing the top of this list before trusting it — a big cluster isn't automatically a good one.

In [12]:
matched.sort("n_primary_ids", descending=True).head(10)

shape: (10, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cluster_i ┆ stable_cl ┆ n_primary ┆ n_hash_id ┆ … ┆ single_ed ┆ n_distinc ┆ n_distinc ┆ n_distin │
│ d         ┆ uster_id  ┆ _ids      ┆ s         ┆   ┆ ge_cluste ┆ t_Borrowe ┆ t_Borrowe ┆ ct_Borro │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ r         ┆ rAddress  ┆ rZip      ┆ werName  │
│ str       ┆ str       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2519      ┆ AUTO_2215 ┆ 56        ┆ 48        ┆ … ┆ false     ┆ 3         ┆ 1         ┆ 45       │
│           ┆ 855951025 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 24726     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1167      ┆ AUTO_1046 ┆ 50        ┆ 49        ┆ … ┆ false     ┆ 3         ┆ 1         ┆ 45       │
│           ┆ 458052020 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 85965     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1690      ┆ AUTO_1499 ┆ 49        ┆ 49        ┆ … ┆ false     ┆ 1         ┆ 2         ┆ 35       │
│           ┆ 079571148 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69028     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3464      ┆ AUTO_3051 ┆ 48        ┆ 48        ┆ … ┆ false     ┆ 1         ┆ 2         ┆ 41       │
│           ┆ 205169451 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 88409     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4397      ┆ AUTO_3882 ┆ 45        ┆ 43        ┆ … ┆ false     ┆ 1         ┆ 1         ┆ 43       │
│           ┆ 825157279 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 79673     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6872      ┆ AUTO_5974 ┆ 42        ┆ 41        ┆ … ┆ false     ┆ 1         ┆ 1         ┆ 41       │
│           ┆ 716029317 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 65632     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8972      ┆ AUTO_7920 ┆ 42        ┆ 42        ┆ … ┆ false     ┆ 3         ┆ 2         ┆ 27       │
│           ┆ 117350087 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47999     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 16851     ┆ AUTO_1522 ┆ 41        ┆ 40        ┆ … ┆ false     ┆ 2         ┆ 1         ┆ 39       │
│           ┆ 889830373 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 392479    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 867       ┆ AUTO_7881 ┆ 37        ┆ 37        ┆ … ┆ false     ┆ 5         ┆ 1         ┆ 23       │
│           ┆ 187824139 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 8370      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18752     ┆ AUTO_1713 ┆ 36        ┆ 32        ┆ … ┆ false     ┆ 6         ┆ 1         ┆ 26       │
│           ┆ 632688415 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 870606    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Inspecting the top cluster

Look at `n_distinct_BorrowerName` vs `n_distinct_BorrowerAddress`/`n_distinct_BorrowerZip` for the largest cluster: if the name count is high while address/zip count is low, this cluster is being held together by a shared address/zip across many *differently named* borrowers — plausible for a shared mailbox address, a franchise HQ, or an office building, but not necessarily the same real-world entity. That's exactly the kind of merge this review table exists to surface.

In [13]:
top_cluster_id = matched.sort("n_primary_ids", descending=True)[0, "cluster_id"]
top_row = matched.filter(pl.col("cluster_id") == top_cluster_id)
print(top_row)

sample = (
    records.filter(pl.col("cluster_id") == top_cluster_id)
    .select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip")
    .unique(subset=["BorrowerName", "BorrowerAddress", "BorrowerZip"])
    .sort("BorrowerName")
)
print(f"\n{sample.height} distinct name/address/zip combos in cluster {top_cluster_id}:")
sample.head(15)

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cluster_i ┆ stable_cl ┆ n_primary ┆ n_hash_id ┆ … ┆ single_ed ┆ n_distinc ┆ n_distinc ┆ n_distin │
│ d         ┆ uster_id  ┆ _ids      ┆ s         ┆   ┆ ge_cluste ┆ t_Borrowe ┆ t_Borrowe ┆ ct_Borro │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ r         ┆ rAddress  ┆ rZip      ┆ werName  │
│ str       ┆ str       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2519      ┆ AUTO_2215 ┆ 56        ┆ 48        ┆ … ┆ false     ┆ 3         ┆ 1         ┆ 45       │
│           ┆ 855951025 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 24726     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

48 distinct name/address/zip combos in cluster 2519:

shape: (15, 4)
┌───────────┬─────────────────────────────────┬─────────────────────────┬─────────────┐
│ record_id ┆ BorrowerName                    ┆ BorrowerAddress         ┆ BorrowerZip │
│ ---       ┆ ---                             ┆ ---                     ┆ ---         │
│ str       ┆ str                             ┆ str                     ┆ str         │
╞═══════════╪═════════════════════════════════╪═════════════════════════╪═════════════╡
│ 538365    ┆ APPLE HOTEL HOLDINGS LLC        ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 545074    ┆ APPLE HOTEL HOLDINGS, LLC       ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 533963    ┆ APPLE HOTEL LLC                 ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 539107    ┆ APPLE HOTEL, LLC                ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 526390    ┆ CITYMARKET HOTEL DEVELOPMENT L… ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 536039    ┆ CLA WEBSTER HOTEL OPERATORS LP  ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 542016    ┆ CLA WEBSTER HOTEL OPERATORS, L… ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 525826    ┆ CONCORD AZTEC BRICKELL LLC      ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 532588    ┆ CONCORD AZTEC SPRINGFIELD LLC   ┆ 11410 COMMON OAKS DRIVE ┆ 27614-7002  │
│ 529485    ┆ CONCORD AZTEC SPRINGFIELD LLC   ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 537396    ┆ CONCORD AZTEC TTC CY LLC        ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 530526    ┆ CONCORD BUCKEYE HOTEL LLC       ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 530940    ┆ CONCORD CLEAR SPRINGS HOTEL LL… ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
│ 534660    ┆ CONCORD CLEAR SPRINGS HOTEL LL… ┆ 11410 COMMON OAKS DR.   ┆ 27614-7002  │
│ 533350    ┆ CONCORD CS CHANDLER LLC         ┆ 11410 COMMON OAKS DR    ┆ 27614-7002  │
└───────────┴─────────────────────────────────┴─────────────────────────┴─────────────┘

## Fragility review

Two views of the same idea: `single_edge_cluster` flags clusters (size >= 2) held together by exactly one qualifying edge. `edge_density` (`n_hash_ids / n_edges`) trends toward its spanning-tree ceiling (~1) the more fragile a cluster is, and drops well below 1 as redundant edges pile up — so among clusters big enough to matter, the highest `edge_density` values are the ones worth a second look.

In [14]:
print("single-edge clusters (size >= 2), largest first:")
matched.filter(pl.col("single_edge_cluster")).sort("n_primary_ids", descending=True).head(10)

single-edge clusters (size >= 2), largest first:

shape: (10, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cluster_i ┆ stable_cl ┆ n_primary ┆ n_hash_id ┆ … ┆ single_ed ┆ n_distinc ┆ n_distinc ┆ n_distin │
│ d         ┆ uster_id  ┆ _ids      ┆ s         ┆   ┆ ge_cluste ┆ t_Borrowe ┆ t_Borrowe ┆ ct_Borro │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ r         ┆ rAddress  ┆ rZip      ┆ werName  │
│ str       ┆ str       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 21472     ┆ AUTO_1984 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 266780526 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 077003    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 17534     ┆ AUTO_1590 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 001380580 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 071038    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 74989     ┆ AUTO_9221 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 673234174 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 852983    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 28773     ┆ AUTO_2733 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 947412901 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 352423    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 61960     ┆ AUTO_6932 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 406963793 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 708063    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 89377     ┆ AUTO_1281 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 420442608 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0811395   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 67876     ┆ AUTO_7900 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 406667628 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 778937    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27424     ┆ AUTO_2585 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 919310167 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 107187    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 53785     ┆ AUTO_5747 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 571347374 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 224573    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 74254     ┆ AUTO_9084 ┆ 4         ┆ 2         ┆ … ┆ true      ┆ 1         ┆ 1         ┆ 2        │
│           ┆ 623332921 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 572449    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
print("most tree-like (fragile) clusters among those with >= 5 rows:")
matched.filter(pl.col("n_primary_ids") >= 5).sort("edge_density", descending=True).head(10)

most tree-like (fragile) clusters among those with >= 5 rows:

shape: (10, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cluster_i ┆ stable_cl ┆ n_primary ┆ n_hash_id ┆ … ┆ single_ed ┆ n_distinc ┆ n_distinc ┆ n_distin │
│ d         ┆ uster_id  ┆ _ids      ┆ s         ┆   ┆ ge_cluste ┆ t_Borrowe ┆ t_Borrowe ┆ ct_Borro │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ r         ┆ rAddress  ┆ rZip      ┆ werName  │
│ str       ┆ str       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1574      ┆ AUTO_1398 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 2         ┆ 1         ┆ 3        │
│           ┆ 180840064 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 41859     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6442      ┆ AUTO_5592 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 2         ┆ 1         ┆ 3        │
│           ┆ 707438366 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 75086     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25774     ┆ AUTO_2413 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 2         ┆ 1         ┆ 3        │
│           ┆ 167760336 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 862134    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 46110     ┆ AUTO_4745 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 1         ┆ 2         ┆ 3        │
│           ┆ 532397288 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 988122    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 59        ┆ AUTO_5298 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 1         ┆ 2         ┆ 3        │
│           ┆ 395916481 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 366       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 47306     ┆ AUTO_4895 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 1         ┆ 2         ┆ 3        │
│           ┆ 489255237 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 488005    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27562     ┆ AUTO_2602 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 2         ┆ 1         ┆ 3        │
│           ┆ 692218126 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 689821    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 15990     ┆ AUTO_1441 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 2         ┆ 1         ┆ 3        │
│           ┆ 596459689 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 610182    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 33571     ┆ AUTO_3269 ┆ 5         ┆ 4         ┆ … ┆ false     ┆ 1         ┆ 2         ┆ 3        │
│           ┆ 402443589 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 915162    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 10663     ┆ AUTO_9444 ┆ 5         ┆ 5         ┆ … ┆ false     ┆ 1         ┆ 3         ┆ 3        │
│           ┆ 348867025 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 90574     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## `thin_edges`

Edges backed by exactly `k_required` signals (no corroboration beyond the minimum bar) vs edges confirmed by more. A cluster where every edge is thin is riskier than one with the same edge count but plenty of doubly-confirmed links.

In [16]:
matched.with_columns(
    thin_edge_share=pl.col("thin_edges") / pl.col("n_edges")
).filter(pl.col("n_primary_ids") >= 5).sort("thin_edge_share", descending=True).head(10)

shape: (10, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cluster_i ┆ stable_cl ┆ n_primary ┆ n_hash_id ┆ … ┆ n_distinc ┆ n_distinc ┆ n_distinc ┆ thin_edg │
│ d         ┆ uster_id  ┆ _ids      ┆ s         ┆   ┆ t_Borrowe ┆ t_Borrowe ┆ t_Borrowe ┆ e_share  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ rAddress  ┆ rZip      ┆ rName     ┆ ---      │
│ str       ┆ str       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ u32       ┆ u32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2519      ┆ AUTO_2215 ┆ 56        ┆ 48        ┆ … ┆ 3         ┆ 1         ┆ 45        ┆ 1.0      │
│           ┆ 855951025 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 24726     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1167      ┆ AUTO_1046 ┆ 50        ┆ 49        ┆ … ┆ 3         ┆ 1         ┆ 45        ┆ 1.0      │
│           ┆ 458052020 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 85965     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1690      ┆ AUTO_1499 ┆ 49        ┆ 49        ┆ … ┆ 1         ┆ 2         ┆ 35        ┆ 1.0      │
│           ┆ 079571148 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69028     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3464      ┆ AUTO_3051 ┆ 48        ┆ 48        ┆ … ┆ 1         ┆ 2         ┆ 41        ┆ 1.0      │
│           ┆ 205169451 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 88409     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4397      ┆ AUTO_3882 ┆ 45        ┆ 43        ┆ … ┆ 1         ┆ 1         ┆ 43        ┆ 1.0      │
│           ┆ 825157279 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 79673     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6872      ┆ AUTO_5974 ┆ 42        ┆ 41        ┆ … ┆ 1         ┆ 1         ┆ 41        ┆ 1.0      │
│           ┆ 716029317 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 65632     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8972      ┆ AUTO_7920 ┆ 42        ┆ 42        ┆ … ┆ 3         ┆ 2         ┆ 27        ┆ 1.0      │
│           ┆ 117350087 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47999     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 16851     ┆ AUTO_1522 ┆ 41        ┆ 40        ┆ … ┆ 2         ┆ 1         ┆ 39        ┆ 1.0      │
│           ┆ 889830373 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 392479    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 867       ┆ AUTO_7881 ┆ 37        ┆ 37        ┆ … ┆ 5         ┆ 1         ┆ 23        ┆ 1.0      │
│           ┆ 187824139 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 8370      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 18752     ┆ AUTO_1713 ┆ 36        ┆ 32        ┆ … ┆ 6         ┆ 1         ┆ 26        ┆ 1.0      │
│           ┆ 632688415 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 870606    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
records['cluster_id'].value_counts().sort('count', descending=True).head(10)

shape: (10, 2)
┌────────────┬───────┐
│ cluster_id ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ 2519       ┆ 56    │
│ 1167       ┆ 50    │
│ 1690       ┆ 49    │
│ 3464       ┆ 48    │
│ 4397       ┆ 45    │
│ 6872       ┆ 42    │
│ 8972       ┆ 42    │
│ 16851      ┆ 41    │
│ 867        ┆ 37    │
│ 796        ┆ 36    │
└────────────┴───────┘

In [19]:
records.filter(pl.col("BorrowerAddress").is_in(["11410 COMMON OAKS DR", "7 PEARL CT"])).select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id", "cluster_id", "stable_cluster_id").sort("BorrowerAddress")

shape: (99, 7)
┌───────────┬──────────────┬──────────────┬─────────────┬──────────────┬────────────┬──────────────┐
│ record_id ┆ BorrowerName ┆ BorrowerAddr ┆ BorrowerZip ┆ hash_id      ┆ cluster_id ┆ stable_clust │
│ ---       ┆ ---          ┆ ess          ┆ ---         ┆ ---          ┆ ---        ┆ er_id        │
│ str       ┆ str          ┆ ---          ┆ str         ┆ u64          ┆ str        ┆ ---          │
│           ┆              ┆ str          ┆             ┆              ┆            ┆ str          │
╞═══════════╪══════════════╪══════════════╪═════════════╪══════════════╪════════════╪══════════════╡
│ 524418    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 918220691388 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ DAYTON HOTEL ┆ OAKS DR      ┆             ┆ 6793362      ┆            ┆ 95102524726  │
│           ┆ II LLC       ┆              ┆             ┆              ┆            ┆              │
│ 525064    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 168097565571 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ SIERRA NLI   ┆ OAKS DR      ┆             ┆ 98628460     ┆            ┆ 95102524726  │
│           ┆ WPB HOTEL L… ┆              ┆             ┆              ┆            ┆              │
│ 525138    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 170617305118 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ DAYTON HOTEL ┆ OAKS DR      ┆             ┆ 59445723     ┆            ┆ 95102524726  │
│           ┆ II, LLC      ┆              ┆             ┆              ┆            ┆              │
│ 525826    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 966787836280 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ AZTEC        ┆ OAKS DR      ┆             ┆ 0026858      ┆            ┆ 95102524726  │
│           ┆ BRICKELL LLC ┆              ┆             ┆              ┆            ┆              │
│ 526332    ┆ CS HOTEL     ┆ 11410 COMMON ┆ 27614-7002  ┆ 154732664729 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ 30W46TH LLC  ┆ OAKS DR      ┆             ┆ 85335431     ┆            ┆ 95102524726  │
│ 526390    ┆ CITYMARKET   ┆ 11410 COMMON ┆ 27614-7002  ┆ 125369808965 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ HOTEL        ┆ OAKS DR      ┆             ┆ 34942630     ┆            ┆ 95102524726  │
│           ┆ DEVELOPMENT  ┆              ┆             ┆              ┆            ┆              │
│           ┆ L…           ┆              ┆             ┆              ┆            ┆              │
│ 527579    ┆ OAKLAND      ┆ 11410 COMMON ┆ 27614-7002  ┆ 121502941213 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ FIFTH AVENUE ┆ OAKS DR      ┆             ┆ 72361915     ┆            ┆ 95102524726  │
│           ┆ HOTEL ASS…   ┆              ┆             ┆              ┆            ┆              │
│ 527660    ┆ CS30W46TH    ┆ 11410 COMMON ┆ 27614-7002  ┆ 744597364069 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ LLC          ┆ OAKS DR      ┆             ┆ 8186408      ┆            ┆ 95102524726  │
│ 527714    ┆ ROSLYN O-S   ┆ 11410 COMMON ┆ 27614-7002  ┆ 109698015391 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ HOTEL        ┆ OAKS DR      ┆             ┆ 71558831     ┆            ┆ 95102524726  │
│           ┆ PARTNERS LLC ┆              ┆             ┆              ┆            ┆              │
│ 528033    ┆ CITYMARKET   ┆ 11410 COMMON ┆ 27614-7002  ┆ 125369808965 ┆ 2519       ┆ AUTO_2215855 │
│           ┆ HOTEL        ┆ OAKS DR      ┆             ┆ 34942630     ┆            ┆ 95102524726  │
│           ┆ DEVELOPMENT  ┆              ┆             ┆              ┆            ┆              │
│           ┆ L…           ┆              ┆             ┆              ┆            ┆              │
│ …         ┆ …            ┆ …            ┆ …           ┆ …            ┆ …          ┆ …            │
│ 574476    ┆ DONEGALS     ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 183725474499 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ IRISH PUB OF ┆              ┆             ┆ 85427157     ┆            ┆ 16945188409  │
│           ┆ RAMSEY, …    ┆              ┆             ┆              ┆            ┆              │
│ 574494    ┆ SPUNTINO OF  ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 161760470670 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ CLIFTON, LLC ┆              ┆             ┆ 80436306     ┆            ┆ 16945188409  │
│ 574523    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 390338322317 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 6382419      ┆            ┆ 16945188409  │
│           ┆ WOODBRID…    ┆              ┆             ┆              ┆            ┆              │
│ 574873    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 179631753770 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 3453591      ┆            ┆ 16945188409  │
│           ┆ PARSIPPA…    ┆              ┆             ┆              ┆            ┆              │
│ 576366    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 396770401103 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 5891572      ┆            ┆ 16945188409  │
│           ┆ WOODMERE…    ┆              ┆             ┆              ┆            ┆              │
│ 576579    ┆ SPUNTINO OF  ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 165340510734 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ NEW YORK,    ┆              ┆             ┆ 82784430     ┆            ┆ 16945188409  │
│           ┆ LLC          ┆              ┆             ┆              ┆            ┆              │
│ 577155    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 100977202945 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 32944271     ┆            ┆ 16945188409  │
│           ┆ BRICK IN…    ┆              ┆             ┆              ┆            ┆              │
│ 577484    ┆ APPLEBEE'S   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 157385873265 ┆ 3464       ┆ AUTO_3051205 │
│           ┆              ┆              ┆             ┆ 21938129     ┆            ┆ 16945188409  │
│ 577587    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 422881651196 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 8705776      ┆            ┆ 16945188409  │
│           ┆ PISCATAW…    ┆              ┆             ┆              ┆            ┆              │
│ 583945    ┆ DOHERTY      ┆ 7 PEARL CT   ┆ 07401-1654  ┆ 168189304122 ┆ 3464       ┆ AUTO_3051205 │
│           ┆ SPECIALTY    ┆              ┆             ┆ 84439531     ┆            ┆ 16945188409  │
│           ┆ BREADS LLC   ┆              ┆             ┆              ┆            ┆              │
└───────────┴──────────────┴──────────────┴─────────────┴──────────────┴────────────┴──────────────┘

In [20]:
address_out['records'].filter(pl.col("BorrowerAddress").is_in(["11410 COMMON OAKS DR", "7 PEARL CT"])).select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id", "cluster_id", "stable_cluster_id").sort("BorrowerAddress")

shape: (99, 7)
┌───────────┬──────────────┬──────────────┬─────────────┬──────────────┬────────────┬──────────────┐
│ record_id ┆ BorrowerName ┆ BorrowerAddr ┆ BorrowerZip ┆ hash_id      ┆ cluster_id ┆ stable_clust │
│ ---       ┆ ---          ┆ ess          ┆ ---         ┆ ---          ┆ ---        ┆ er_id        │
│ str       ┆ str          ┆ ---          ┆ str         ┆ u64          ┆ str        ┆ ---          │
│           ┆              ┆ str          ┆             ┆              ┆            ┆ str          │
╞═══════════╪══════════════╪══════════════╪═════════════╪══════════════╪════════════╪══════════════╡
│ 524418    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 918220691388 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ DAYTON HOTEL ┆ OAKS DR      ┆             ┆ 6793362      ┆            ┆ 01           │
│           ┆ II LLC       ┆              ┆             ┆              ┆            ┆              │
│ 525064    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 168097565571 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SIERRA NLI   ┆ OAKS DR      ┆             ┆ 98628460     ┆            ┆ 01           │
│           ┆ WPB HOTEL L… ┆              ┆             ┆              ┆            ┆              │
│ 525138    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 170617305118 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ DAYTON HOTEL ┆ OAKS DR      ┆             ┆ 59445723     ┆            ┆ 01           │
│           ┆ II, LLC      ┆              ┆             ┆              ┆            ┆              │
│ 525826    ┆ CONCORD      ┆ 11410 COMMON ┆ 27614-7002  ┆ 966787836280 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ AZTEC        ┆ OAKS DR      ┆             ┆ 0026858      ┆            ┆ 01           │
│           ┆ BRICKELL LLC ┆              ┆             ┆              ┆            ┆              │
│ 526332    ┆ CS HOTEL     ┆ 11410 COMMON ┆ 27614-7002  ┆ 154732664729 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ 30W46TH LLC  ┆ OAKS DR      ┆             ┆ 85335431     ┆            ┆ 01           │
│ 526390    ┆ CITYMARKET   ┆ 11410 COMMON ┆ 27614-7002  ┆ 125369808965 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ HOTEL        ┆ OAKS DR      ┆             ┆ 34942630     ┆            ┆ 01           │
│           ┆ DEVELOPMENT  ┆              ┆             ┆              ┆            ┆              │
│           ┆ L…           ┆              ┆             ┆              ┆            ┆              │
│ 527579    ┆ OAKLAND      ┆ 11410 COMMON ┆ 27614-7002  ┆ 121502941213 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ FIFTH AVENUE ┆ OAKS DR      ┆             ┆ 72361915     ┆            ┆ 01           │
│           ┆ HOTEL ASS…   ┆              ┆             ┆              ┆            ┆              │
│ 527660    ┆ CS30W46TH    ┆ 11410 COMMON ┆ 27614-7002  ┆ 744597364069 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ LLC          ┆ OAKS DR      ┆             ┆ 8186408      ┆            ┆ 01           │
│ 527714    ┆ ROSLYN O-S   ┆ 11410 COMMON ┆ 27614-7002  ┆ 109698015391 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ HOTEL        ┆ OAKS DR      ┆             ┆ 71558831     ┆            ┆ 01           │
│           ┆ PARTNERS LLC ┆              ┆             ┆              ┆            ┆              │
│ 528033    ┆ CITYMARKET   ┆ 11410 COMMON ┆ 27614-7002  ┆ 125369808965 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ HOTEL        ┆ OAKS DR      ┆             ┆ 34942630     ┆            ┆ 01           │
│           ┆ DEVELOPMENT  ┆              ┆             ┆              ┆            ┆              │
│           ┆ L…           ┆              ┆             ┆              ┆            ┆              │
│ …         ┆ …            ┆ …            ┆ …           ┆ …            ┆ …          ┆ …            │
│ 574476    ┆ DONEGALS     ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 183725474499 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ IRISH PUB OF ┆              ┆             ┆ 85427157     ┆            ┆ 01           │
│           ┆ RAMSEY, …    ┆              ┆             ┆              ┆            ┆              │
│ 574494    ┆ SPUNTINO OF  ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 161760470670 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ CLIFTON, LLC ┆              ┆             ┆ 80436306     ┆            ┆ 01           │
│ 574523    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 390338322317 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 6382419      ┆            ┆ 01           │
│           ┆ WOODBRID…    ┆              ┆             ┆              ┆            ┆              │
│ 574873    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 179631753770 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 3453591      ┆            ┆ 01           │
│           ┆ PARSIPPA…    ┆              ┆             ┆              ┆            ┆              │
│ 576366    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 396770401103 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 5891572      ┆            ┆ 01           │
│           ┆ WOODMERE…    ┆              ┆             ┆              ┆            ┆              │
│ 576579    ┆ SPUNTINO OF  ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 165340510734 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ NEW YORK,    ┆              ┆             ┆ 82784430     ┆            ┆ 01           │
│           ┆ LLC          ┆              ┆             ┆              ┆            ┆              │
│ 577155    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 100977202945 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 32944271     ┆            ┆ 01           │
│           ┆ BRICK IN…    ┆              ┆             ┆              ┆            ┆              │
│ 577484    ┆ APPLEBEE'S   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 157385873265 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆              ┆              ┆             ┆ 21938129     ┆            ┆ 01           │
│ 577587    ┆ APPLE FOOD   ┆ 7 PEARL CT   ┆ 07401-1610  ┆ 422881651196 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SERVICE OF   ┆              ┆             ┆ 8705776      ┆            ┆ 01           │
│           ┆ PISCATAW…    ┆              ┆             ┆              ┆            ┆              │
│ 583945    ┆ DOHERTY      ┆ 7 PEARL CT   ┆ 07401-1654  ┆ 168189304122 ┆ 2519       ┆ ADDR_ALIAS_0 │
│           ┆ SPECIALTY    ┆              ┆             ┆ 84439531     ┆            ┆ 01           │
│           ┆ BREADS LLC   ┆              ┆             ┆              ┆            ┆              │
└───────────┴──────────────┴──────────────┴─────────────┴──────────────┴────────────┴──────────────┘

In [ ]:
records.filter(pl.col("cluster_id") == "2622").select("record_id", "BorrowerName", "BorrowerAddress", "BorrowerZip", "hash_id").unique(subset=["BorrowerName", "BorrowerAddress", "BorrowerZip"]).sort("BorrowerName")

shape: (3, 5)
┌───────────┬────────────────────────┬────────────────────────┬─────────────┬──────────────────────┐
│ record_id ┆ BorrowerName           ┆ BorrowerAddress        ┆ BorrowerZip ┆ hash_id              │
│ ---       ┆ ---                    ┆ ---                    ┆ ---         ┆ ---                  │
│ str       ┆ str                    ┆ str                    ┆ str         ┆ u64                  │
╞═══════════╪════════════════════════╪════════════════════════╪═════════════╪══════════════════════╡
│ 646876    ┆ FRIEDWALD CENTER FOR   ┆ 475 NEW HEMPSTEAD ROAD ┆ 10956       ┆ 6187453111763336785  │
│           ┆ DIALYSIS,…             ┆                        ┆             ┆                      │
│ 607174    ┆ FRIEDWALD CENTER FOR   ┆ 475 NEW HEMPSTEAD ROAD ┆ 10956       ┆ 18086546270986880475 │
│           ┆ REHABILIT…             ┆                        ┆             ┆                      │
│ 660108    ┆ SUMMIT AT FRIEDWALD    ┆ 475 NEW HEMPSTEAD ROAD ┆ 10956       ┆ 10183094102775570983 │
│           ┆ CARE CENTE…            ┆                        ┆             ┆                      │
└───────────┴────────────────────────┴────────────────────────┴─────────────┴──────────────────────┘

In [ ]:
records.filter(pl.col("hash_id") == 12160495072962979024)

shape: (1, 56)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ record_id ┆ LoanNumbe ┆ DateAppro ┆ SBAOffice ┆ … ┆ Forgivene ┆ Forgivene ┆ hash_id   ┆ cluster_ │
│ ---       ┆ r         ┆ ved       ┆ Code      ┆   ┆ ssAmount  ┆ ssDate    ┆ ---       ┆ id       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u64       ┆ ---      │
│           ┆ i64       ┆ str       ┆ i64       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 529485    ┆ 290955850 ┆ 02/22/202 ┆ 460       ┆ … ┆ 477451.26 ┆ 04/21/202 ┆ 121604950 ┆ 4750     │
│           ┆ 4         ┆ 1         ┆           ┆   ┆           ┆ 2         ┆ 729629790 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 24        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘